/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

/**
 *
 * @author USER
 */
public class SeleccionarNivel extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarPrincipiante
     */
    public SeleccionarNivel() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnAvanzado = new javax.swing.JButton();
        jbtnIntermedio = new javax.swing.JButton();
        jbtnPrincipiante = new javax.swing.JButton();
        jbtnRegresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnAvanzado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnAvanzado.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAvanzado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ButtonAvanzado.png"))); // NOI18N
        jbtnAvanzado.setBorder(null);
        jbtnAvanzado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAvanzadoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAvanzado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 200, 100));

        jbtnIntermedio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnIntermedio.setForeground(new java.awt.Color(255, 255, 255));
        jbtnIntermedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ButtonIntermedio.png"))); // NOI18N
        jbtnIntermedio.setBorder(null);
        jbtnIntermedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIntermedioActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnIntermedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 190, 110));

        jbtnPrincipiante.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jbtnPrincipiante.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPrincipiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ButtonPrincipiante (2).png"))); // NOI18N
        jbtnPrincipiante.setBorder(null);
        jbtnPrincipiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrincipianteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPrincipiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 190, 110));

        jbtnRegresar.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jbtnRegresar.setText("<--   Regresar");
        jbtnRegresar.setBorder(null);
        jbtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 140, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Desktop - 43.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegresarActionPerformed
        Menu menu = new Menu(Menu.user);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnRegresarActionPerformed

    private void jbtnIntermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIntermedioActionPerformed
        SeleccionarIntermedio intermedio = new SeleccionarIntermedio();
        intermedio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnIntermedioActionPerformed

    private void jbtnPrincipianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrincipianteActionPerformed
        SeleccionarPrincipiante principiante = new SeleccionarPrincipiante();
        principiante.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnPrincipianteActionPerformed

    private void jbtnAvanzadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAvanzadoActionPerformed
        SeleccionarAvanzado avanzado = new SeleccionarAvanzado();
        avanzado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnAvanzadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarNivel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtnAvanzado;
    private javax.swing.JButton jbtnIntermedio;
    private javax.swing.JButton jbtnPrincipiante;
    private javax.swing.JButton jbtnRegresar;
    // End of variables declaration//GEN-END:variables
}
