/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Pantallas.Indicaciones.*;

/**
 *
 * @author USER
 */
public class SeleccionarPrincipiante extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarPrincipiante
     */
    public SeleccionarPrincipiante() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnRegresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnSaludo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtnAnimales = new javax.swing.JButton();
        jbtnSemana = new javax.swing.JButton();
        jbtnColores = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnRegresar.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        jbtnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        jbtnRegresar.setText("<--   Regresar");
        jbtnRegresar.setBorder(null);
        jbtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Img.Semana.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Img.Colores.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Img.Saludo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jbtnSaludo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnSaludo.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSaludo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ButtonSaludos.png"))); // NOI18N
        jbtnSaludo.setBorder(null);
        jbtnSaludo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaludoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSaludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 190, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Img.Animal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        jbtnAnimales.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnAnimales.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAnimales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ButtonAnimales.png"))); // NOI18N
        jbtnAnimales.setBorder(null);
        jbtnAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAnimalesActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAnimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 190, 120));

        jbtnSemana.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jbtnSemana.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSemana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ButtonDiSemana.png"))); // NOI18N
        jbtnSemana.setBorder(null);
        jbtnSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSemanaActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 180, 120));

        jbtnColores.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnColores.setForeground(new java.awt.Color(255, 255, 255));
        jbtnColores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ButtonColores.png"))); // NOI18N
        jbtnColores.setBorder(null);
        jbtnColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnColoresActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnColores, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 180, 120));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Desktop - 44.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegresarActionPerformed
        SeleccionarNivel menu = new SeleccionarNivel();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnRegresarActionPerformed

    private void jbtnColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnColoresActionPerformed
        I_Principiante_Colores ejercicio = new I_Principiante_Colores();
        ejercicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnColoresActionPerformed

    private void jbtnSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSemanaActionPerformed
        I_Principiante_Semana ejercicio = new I_Principiante_Semana();
        ejercicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnSemanaActionPerformed

    private void jbtnSaludoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaludoActionPerformed
        I_Principiante_Saludo ejercicio = new I_Principiante_Saludo();
        ejercicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnSaludoActionPerformed

    private void jbtnAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAnimalesActionPerformed
        I_Principiante_Animales ejercicio = new I_Principiante_Animales();
        ejercicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnAnimalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarPrincipiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtnAnimales;
    private javax.swing.JButton jbtnColores;
    private javax.swing.JButton jbtnRegresar;
    private javax.swing.JButton jbtnSaludo;
    private javax.swing.JButton jbtnSemana;
    // End of variables declaration//GEN-END:variables
}
