/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Pantallas.Indicaciones.*;
import javax.swing.JButton;

/**
 *
 * @author USER
 */
public class SeleccionarAvanzado extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarPrincipiante
     */
    public SeleccionarAvanzado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnCuerpo = new javax.swing.JButton();
        jbtnSufijo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtnDialogo = new javax.swing.JButton();
        jbtnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 607, -1));

        jbtnCuerpo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnCuerpo.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCuerpo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ButtonPartesHumanas.png"))); // NOI18N
        jbtnCuerpo.setBorder(null);
        jbtnCuerpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCuerpoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 220, 100));

        jbtnSufijo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnSufijo.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSufijo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ButtonSufijo.png"))); // NOI18N
        jbtnSufijo.setBorder(null);
        jbtnSufijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSufijoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSufijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 210, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/NIñoDialog.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jbtnDialogo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDialogo.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDialogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ButtonDialogos.png"))); // NOI18N
        jbtnDialogo.setBorder(null);
        jbtnDialogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDialogoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDialogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 190, 120));

        jbtnRegresar.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        jbtnRegresar.setText("<--   Regresar");
        jbtnRegresar.setBorder(null);
        jbtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Desktop - 41.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCuerpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCuerpoActionPerformed
    I_Avanzado_PartesCuerpo ejercicio = new I_Avanzado_PartesCuerpo();
    ejercicio.setVisible(true);
    this.dispose();   
    }//GEN-LAST:event_jbtnCuerpoActionPerformed

    private void jbtnDialogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDialogoActionPerformed
    I_Avanzado_Dialogo ejercicio = new I_Avanzado_Dialogo();
    ejercicio.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jbtnDialogoActionPerformed

    private void jbtnSufijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSufijoActionPerformed
    I_Avanzado_Sufijo ejercicio = new I_Avanzado_Sufijo();
    ejercicio.setVisible(true);
    this.dispose();     
    }//GEN-LAST:event_jbtnSufijoActionPerformed

    private void jbtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegresarActionPerformed
        SeleccionarNivel menu = new SeleccionarNivel();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarAvanzado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnCuerpo;
    private javax.swing.JButton jbtnDialogo;
    private javax.swing.JButton jbtnRegresar;
    private javax.swing.JButton jbtnSufijo;
    // End of variables declaration//GEN-END:variables
}
